import pygame

class Scene:
    def __init__(self) -> None:
        self.display_surface = pygame.display.get_surface()
        self.width = self.display_surface.get_width()
        self.height = self.display_surface.get_height()

        self.half_width = self.width / 2
        self.half_height = self.height / 2
    def on_enter(self) -> None: ...
    def on_update(self) -> None: ...
    def on_draw(self) -> None: ...
    def on_input(self, event) -> None: ...
    def on_exit(self) -> None: ...